sudo: required
services:
  - docker

before_install:
  - docker build -t neha1706/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run neha1706/react-test npm test -- --coverage

after_success:
  - docker build -t neha1706/complex-client ./client
  - docker build -t neha1706/complex-nginx ./nginx
  - docker build -t neha1706/complex-server ./server
  - docker build -t neha1706/complex-worker ./worker
  # Log in to the docker CLI again
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push neha1706/complex-client
  - docker push neha1706/complex-nginx
  - docker push neha1706/complex-server
  - docker push neha1706/complex-worker

deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: docker_complex
    env: DockerComplex-env
    bucket_name: elasticbeanstalk-us-east-2-561199268779
    bucket_path: complex_docker
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: $AWS_SECRET_KEY
